apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- clusterrolebinding.yaml
- https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
namespace: argo-rollouts
