apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCND0lc9fcABwm6wuy+H/88U/unySgcnnj7EuJAlX9sg/2FhCQ2j/3wS7Ha+l9KtUVak2Aidt3csWsO14cvQ7NmovOfGHLcMqTSwuxhXZuVaJPY+t6Cn2mL175jOko7ZDtz9aaCYpY93rHMLvszKForjOy/M603Q+LrndyoqS0GmCykw5nj8D3cvKO0jzNAndypGu4YT8gbQTcw/FrdHq2rYwMgE0ZyPJxb396uPbGhgMl/aThhpy9TcUe3j6tG4LiJ+99wTUmIeuM2oEQH8mAfkguYFpy0nfd4uJG5iiS46eUPH+gxQu143t7hREJHMmeMJQKN8zmkKZdatv6J4sEmAyP7ibn8+dKPNlwFqNqVVL6G1Tf2BFnUS5ztVp6Rt5J/8vbO11dwRjIhbPNS4NaKSpDvqdea2VawFwX/BB8zqHz1afjqvr4jG2joU4lptgutj2bQz9Eb2orYHod3qYKZ2nYXtbscK9UyzttGgiEZVmY1UvWgsqiXr5x3Rx/paiXA4uZ3HeoUFwS/1ZVw2rs0JD+0EmTU91+pmW77spi5T+XcCpPofuZwXjIJ+bRm8UHdWdPA4ySzm/TzbUX2uwg5FjT4G0Td9+sYDBguz03p0D6DKGlHczQg3E2ipiFZ+w1Uh9U/K3y0jei4kLkaDOg22gOzeMTQAhzE7QTu2S5Fz/ViqH4UcWPErwaLcPlZcQrvt1BF0FP5GB1srZrx7XwmHulxFBOfiuGFEpDKY/Zd0uBX+LukJXWWF8sU3PH53a/XsIm9TTrY1McvMI8dybiGYxgBPO4j3+dk0v4Nl7pgDn5hV+e7/3lXWPAyWJNatCNrSZ9mBk/kxdoZ43IO+QzD1rf9yet6YXlOGU6JsPIAKluBzf8Q3rYsDT6909obAMaW/pYHdJdFAzIIp+o=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

