apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/ec-doris/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - raphdom/argo-combined-app:4ac73d51fc02e825f4c47a4bdc938af2af8e3b82
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
