apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rbac.yaml
- raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
- event-bus.yaml
namespace: argo-events

