apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAsXFkrRpNd59BvLxqz0GPbtnLsrZw5NmNkHkMh4kgMoMlaRgEB2e9U9oe20pnwe8hQ9iJR3Uqgh6XL24qBAHRoxHPPOFmYGVLIRy/sWK+lqQz3kHBtDwHIuDYv/ihu1ZqeuzIq4K2eBHGKfsg2CIEfp/QpSM2xkLI0G+q9/rJZexulyPsXEozX6VXjCyH4b+1hM1EqeDivnG9kxSunmK1w2XAKfY5BBC8Xl/Hb+wOZMsSZk1gxDN7axiWHVXAFK9gsyGfNxeE6erap9/zh3fpQXCwpIOP/RfYhYF1eWTUTm9DBGzMR52at/mgoQb3zzJEBe0cV7WxBCGYEkhKOgQ3PsLeeWXyLBMJ6bInj674+hyxPlhm1arygr0mk+GJSt4PrH30mhedDBnEeSgXEggEPDsch00tv19f+Fsu801gJd/qo+tB0doAGnyOCyLPWKGzP9sF2CMjm9TQJXUUXIHdWw7ZyGynvLazi+xc1FYq7d8r7E0ZJl5W1HpOUcx5O9PG+lyjwdxSSoxrdtKA9Qn4Cbm5LyIO1EA+ohDn3nqyRhGiQ9DV0nV56W3TFm4rolMg7aAgAnvsb13ygcd57P9ZoVVohB+Jik7AatkF1sR8Npx+Osu/lPIYk+3luUPvuYjPONWw/LStV87fiGp7+79WZQvUPD08X1Zoev5pFW13l+rbmfjF/3o6snV8jOgD448nuva21qE87e99ESbneVxsJiCcAq9xXlQO4z2bzfeGC2s9OJgebOyP2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

